[build]
builder = "nixpacks"
buildCommand = "npm install && npx prisma generate && npx prisma db push && npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/login"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[service]
internalPort = 3000
